/**
 * Stop Message Loss — Reproduction Tests
 *
 * Confirms that assistant messages are silently deleted from the database
 * when the frontend's assistant message IDs don't match the server-side DB
 * message IDs. This happens because:
 *
 *   1. The server saves assistant messages with UUIDs generated by createMessage().
 *   2. The frontend (AI SDK stream) creates assistant messages with DIFFERENT
 *      UUIDs generated by toUIMessageStreamResponse() / generateId().
 *   3. On the NEXT POST /api/chat, deleteMessagesNotIn() receives the frontend's
 *      IDs, doesn't recognise the DB's assistant message IDs, and deletes them
 *      because they fall after the last matched position (maxKeptPosition).
 *
 * Over multiple turns every previous assistant message is wiped from the DB.
 * The user never notices until:
 *   - They press Stop (handlePostCancel reloads from DB → messages gone from UI)
 *   - They export the session (reads from DB → assistant messages missing)
 *   - They reload the page
 *
 * Related Bug: Branch creation on Stop ("← 2 / 2 →") is a downstream symptom.
 * When handlePostCancel reloads the incomplete DB history into assistant-ui's
 * MessageRepository via chat.setMessages(), the ID mismatch causes the repo
 * to create phantom branches instead of a clean linear thread.
 */

import { describe, it, expect, beforeEach } from "vitest";
import {
  createSession,
  createMessage,
  getMessages,
  getOrCreateLocalUser,
  deleteMessagesNotIn,
} from "@/lib/db/queries";

describe("Stop Message Loss — ID Mismatch Bug", () => {
  const TEST_USER_ID = "test-user-stop-loss";
  const TEST_EMAIL = "test-stop-loss@example.com";

  beforeEach(async () => {
    await getOrCreateLocalUser(TEST_USER_ID, TEST_EMAIL);
  });

  it("BUG REPRO: deleteMessagesNotIn deletes assistant messages when frontend IDs don't match DB IDs", async () => {
    // ── Setup: Simulate a 2-turn conversation as stored in the DB ────────
    const session = await createSession({ title: "Stop Loss Test", userId: TEST_USER_ID });
    if (!session) throw new Error("Failed to create session");

    // Turn 1: User message (ID matches frontend — user IDs are sent in the request body)
    const user1Id = crypto.randomUUID();
    await createMessage({
      id: user1Id,
      sessionId: session.id,
      role: "user",
      content: [{ type: "text", text: "Fix the progression bug (plan only)" }],
      orderingIndex: 1,
    });

    // Turn 1: Assistant response (ID generated server-side by createMessage/onFinish)
    const serverAssistant1Id = crypto.randomUUID();
    await createMessage({
      id: serverAssistant1Id,
      sessionId: session.id,
      role: "assistant",
      content: [{ type: "text", text: "Here's my plan for the fix..." }],
      orderingIndex: 2,
    });

    // Verify both messages exist
    let allMessages = await getMessages(session.id);
    expect(allMessages).toHaveLength(2);

    // ── Simulate Turn 2: Frontend sends a new message ────────────────────
    // The frontend has a DIFFERENT UUID for the assistant message (generated
    // by the AI SDK stream, not from the DB).
    const frontendAssistant1Id = crypto.randomUUID(); // ≠ serverAssistant1Id
    const user2Id = crypto.randomUUID();

    // Frontend sends: [user1(user1Id), assistant1(frontendAssistant1Id), user2(user2Id)]
    // Only user1Id matches a DB row. frontendAssistant1Id ≠ serverAssistant1Id.
    // user2Id is new (not yet in DB — it's saved AFTER deleteMessagesNotIn).
    const frontendIds = new Set([user1Id, frontendAssistant1Id, user2Id]);

    // ── This is the exact call the chat API route makes at line 383 ──────
    const deleted = await deleteMessagesNotIn(session.id, frontendIds);

    // ── Assertion: The assistant message SHOULD NOT have been deleted ─────
    // BUG: It IS deleted because frontendAssistant1Id ≠ serverAssistant1Id
    allMessages = await getMessages(session.id);
    const assistantMessages = allMessages.filter((m) => m.role === "assistant");

    // This assertion demonstrates the bug:
    // If this FAILS (deleted === 1, assistantMessages.length === 0), the bug exists.
    // If this PASSES, the bug has been fixed.
    expect(deleted).toBe(0);
    expect(assistantMessages).toHaveLength(1);
    expect(assistantMessages[0]?.id).toBe(serverAssistant1Id);
  });

  it("BUG REPRO: Multi-turn conversation loses ALL assistant messages over time", async () => {
    const session = await createSession({ title: "Multi-Turn Loss", userId: TEST_USER_ID });
    if (!session) throw new Error("Failed to create session");

    // ── Turn 1 ───────────────────────────────────────────────────────────
    const user1Id = crypto.randomUUID();
    await createMessage({ id: user1Id, sessionId: session.id, role: "user", content: [{ type: "text", text: "User message 1" }], orderingIndex: 1 });

    const serverAsst1Id = crypto.randomUUID();
    await createMessage({ id: serverAsst1Id, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Assistant response 1" }], orderingIndex: 2 });

    // Frontend IDs for assistant message are different
    const frontendAsst1Id = crypto.randomUUID();

    // ── Turn 2: deleteMessagesNotIn runs before user2 is saved ───────────
    const user2Id = crypto.randomUUID();
    const frontendIds2 = new Set([user1Id, frontendAsst1Id, user2Id]);
    await deleteMessagesNotIn(session.id, frontendIds2);

    // Save user2 (happens after deleteMessagesNotIn in the real route)
    await createMessage({ id: user2Id, sessionId: session.id, role: "user", content: [{ type: "text", text: "User message 2" }], orderingIndex: 3 });

    const serverAsst2Id = crypto.randomUUID();
    await createMessage({ id: serverAsst2Id, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Assistant response 2" }], orderingIndex: 4 });

    const frontendAsst2Id = crypto.randomUUID();

    // ── Turn 3: deleteMessagesNotIn runs again ───────────────────────────
    const user3Id = crypto.randomUUID();
    const frontendIds3 = new Set([user1Id, frontendAsst1Id, user2Id, frontendAsst2Id, user3Id]);
    await deleteMessagesNotIn(session.id, frontendIds3);

    // Save user3
    await createMessage({ id: user3Id, sessionId: session.id, role: "user", content: [{ type: "text", text: "User message 3" }], orderingIndex: 5 });

    // Simulate Stop: onAbort saves system interruption message
    await createMessage({ sessionId: session.id, role: "system", content: [{ type: "text", text: "Process interrupted by user" }], orderingIndex: 6 });

    // ── Verify final DB state ────────────────────────────────────────────
    const finalMessages = await getMessages(session.id);
    const roles = finalMessages.map((m) => m.role);
    const indices = finalMessages.map((m) => m.orderingIndex);

    // BUG: If both assistant messages were deleted, we'd see:
    //   roles = ["user", "user", "user", "system"]
    //   indices = [1, 3, 5, 6]  ← MATCHES THE USER'S EXACT BUG REPORT
    //
    // EXPECTED (correct behavior):
    //   roles = ["user", "assistant", "user", "assistant", "user", "system"]
    //   indices = [1, 2, 3, 4, 5, 6]
    expect(roles).toEqual(["user", "assistant", "user", "assistant", "user", "system"]);
    expect(indices).toEqual([1, 2, 3, 4, 5, 6]);
  });

  it("CONTROL: deleteMessagesNotIn works correctly when assistant IDs match", async () => {
    const session = await createSession({ title: "Matching IDs Control", userId: TEST_USER_ID });
    if (!session) throw new Error("Failed to create session");

    const user1Id = crypto.randomUUID();
    await createMessage({ id: user1Id, sessionId: session.id, role: "user", content: [{ type: "text", text: "User 1" }], orderingIndex: 1 });

    const asst1Id = crypto.randomUUID();
    await createMessage({ id: asst1Id, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Asst 1" }], orderingIndex: 2 });

    const user2Id = crypto.randomUUID();
    await createMessage({ id: user2Id, sessionId: session.id, role: "user", content: [{ type: "text", text: "User 2" }], orderingIndex: 3 });

    const asst2Id = crypto.randomUUID();
    await createMessage({ id: asst2Id, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Asst 2" }], orderingIndex: 4 });

    // When IDs match (ideal scenario), nothing should be deleted
    const user3Id = crypto.randomUUID();
    const frontendIds = new Set([user1Id, asst1Id, user2Id, asst2Id, user3Id]);
    const deleted = await deleteMessagesNotIn(session.id, frontendIds);

    expect(deleted).toBe(0);

    const allMessages = await getMessages(session.id);
    expect(allMessages).toHaveLength(4);
    expect(allMessages.filter((m) => m.role === "assistant")).toHaveLength(2);
  });

  it("BUG REPRO: Verifies exact indices from user's bug report (1,3,5,6)", async () => {
    // Simulates the EXACT scenario from the user's bug report:
    // 3 user messages, 2 assistant responses that got deleted, 1 system interruption
    const session = await createSession({ title: "Exact Bug Report Repro", userId: TEST_USER_ID });
    if (!session) throw new Error("Failed to create session");

    // ── Server-side DB state after Turn 1 ────────────────────────────────
    const u1 = crypto.randomUUID();
    await createMessage({ id: u1, sessionId: session.id, role: "user", content: [{ type: "text", text: "Fix the unanswered question progression bug (plan only)" }], orderingIndex: 1 });
    const a1_server = crypto.randomUUID();
    await createMessage({ id: a1_server, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Here's the plan..." }], orderingIndex: 2 });

    // ── Turn 2: Frontend sends new message. Assistant ID mismatched. ─────
    const a1_frontend = crypto.randomUUID(); // Different from a1_server!
    const u2 = crypto.randomUUID();
    await deleteMessagesNotIn(session.id, new Set([u1, a1_frontend, u2]));
    await createMessage({ id: u2, sessionId: session.id, role: "user", content: [{ type: "text", text: "implement, no need for a ticket" }], orderingIndex: 3 });
    const a2_server = crypto.randomUUID();
    await createMessage({ id: a2_server, sessionId: session.id, role: "assistant", content: [{ type: "text", text: "Implementing now..." }], orderingIndex: 4 });

    // ── Turn 3: Frontend sends new message. Assistant ID mismatched. ─────
    const a2_frontend = crypto.randomUUID(); // Different from a2_server!
    const u3 = crypto.randomUUID();
    await deleteMessagesNotIn(session.id, new Set([u1, a1_frontend, u2, a2_frontend, u3]));
    await createMessage({ id: u3, sessionId: session.id, role: "user", content: [{ type: "text", text: "but shortcuts are not working any more after your change" }], orderingIndex: 5 });

    // ── Stop pressed: onAbort saves system interruption ──────────────────
    await createMessage({ sessionId: session.id, role: "system", content: [{ type: "text", text: "Process interrupted by user" }], orderingIndex: 6 });

    // ── Final state: the user's exact bug report ─────────────────────────
    const final = await getMessages(session.id);
    const finalRoles = final.map((m) => m.role);
    const finalIndices = final.map((m) => m.orderingIndex);

    // If the bug exists, we see exactly what the user reported:
    //   roles = ["user", "user", "user", "system"]
    //   indices = [1, 3, 5, 6]
    //
    // Log the actual state for diagnostic clarity
    console.log("Final DB state:", JSON.stringify({ roles: finalRoles, indices: finalIndices }));

    // The CORRECT state should be:
    expect(finalRoles).toEqual(["user", "assistant", "user", "assistant", "user", "system"]);
    expect(finalIndices).toEqual([1, 2, 3, 4, 5, 6]);
  });
});
