import type { CatalogSkill, CatalogSkillCollection } from "./types";
import { AGENCY_AGENTS_COLLECTION, AGENCY_AGENTS_SKILLS } from "./agency-agents";
import { SYSTEM_SKILLS } from "./system-skills";

export const SKILL_CATALOG: CatalogSkill[] = [
  {
    id: "prompt-enhancer",
    displayName: "Prompt Enhancer",
    shortDescription: "Enrich prompts with codebase context for grounded, actionable results",
    category: "dev-tools",
    icon: "prompt-enhancer.svg",
    defaultPrompt: "Enhance my prompt with relevant codebase context from synced folders.",
    installSource: { type: "bundled" },
    tags: ["enhance", "prompt", "context", "codebase", "grounding"],
  },
  {
    id: "figma",
    displayName: "Figma",
    shortDescription: "Use Figma MCP for design-to-code work",
    category: "design",
    icon: "figma.png",
    defaultPrompt: "Use Figma MCP to inspect the target design and translate it into implementable UI decisions.",
    dependencies: [{ type: "mcp", value: "figma", description: "Figma MCP server", url: "https://mcp.figma.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["figma", "design", "ui"],
  },
  {
    id: "figma-implement-design",
    displayName: "Figma Implement Design",
    shortDescription: "Turn Figma designs into production-ready code",
    category: "design",
    icon: "figma.png",
    defaultPrompt: "Implement this Figma design in this codebase, matching layout, states, and responsive behavior.",
    dependencies: [{ type: "mcp", value: "figma", description: "Figma MCP server", url: "https://mcp.figma.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["figma", "implementation", "frontend"],
  },
  {
    id: "vercel-deploy",
    displayName: "Vercel Deploy",
    shortDescription: "Deploy apps with zero configuration on Vercel",
    category: "deploy",
    icon: "vercel.png",
    defaultPrompt: "Create a Vercel deployment for this project and share the URL.",
    installSource: { type: "bundled" },
    tags: ["vercel", "deploy"],
  },
  {
    id: "netlify-deploy",
    displayName: "Netlify Deploy",
    shortDescription: "Deploy web projects to Netlify",
    category: "deploy",
    icon: "netlify.png",
    defaultPrompt: "Deploy this project to Netlify and return the preview URL, build settings, and required fixes.",
    installSource: { type: "bundled" },
    tags: ["netlify", "deploy"],
  },
  {
    id: "cloudflare-deploy",
    displayName: "Cloudflare Deploy",
    shortDescription: "Deploy Workers and Pages on Cloudflare",
    category: "deploy",
    icon: "cloudflare.png",
    defaultPrompt: "Deploy this app to Cloudflare (Workers or Pages) and return URL, config, and required env vars.",
    installSource: { type: "bundled" },
    tags: ["cloudflare", "deploy"],
  },
  {
    id: "render-deploy",
    displayName: "Render Deploy",
    shortDescription: "Deploy applications to Render",
    category: "deploy",
    icon: "render.png",
    defaultPrompt: "Deploy this application to Render and provide service URL, env vars, and next checks.",
    dependencies: [{ type: "mcp", value: "render", description: "Render MCP server", url: "https://mcp.render.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["render", "deploy"],
  },
  {
    id: "gh-fix-ci",
    displayName: "GitHub Fix CI",
    shortDescription: "Debug failing GitHub Actions checks",
    category: "dev-tools",
    icon: "github.png",
    defaultPrompt: "Inspect failing GitHub Actions checks in this repo, summarize root cause, and propose a focused fix plan.",
    installSource: { type: "bundled" },
    tags: ["github", "ci"],
  },
  {
    id: "gh-address-comments",
    displayName: "GitHub Address Comments",
    shortDescription: "Address comments in a GitHub PR review",
    category: "dev-tools",
    icon: "github.png",
    defaultPrompt: "Address all actionable GitHub PR review comments in this branch and summarize the updates.",
    installSource: { type: "bundled" },
    tags: ["github", "pr", "review"],
  },
  {
    id: "linear",
    displayName: "Linear",
    shortDescription: "Manage Linear issues",
    category: "dev-tools",
    icon: "linear.png",
    defaultPrompt: "Use Linear context to triage or update relevant issues for this task, with clear next actions.",
    dependencies: [{ type: "mcp", value: "linear", description: "Linear MCP server", url: "https://mcp.linear.app/mcp" }],
    installSource: { type: "bundled" },
    tags: ["linear", "issues"],
  },
  {
    id: "sentry",
    displayName: "Sentry",
    shortDescription: "Read-only Sentry observability",
    category: "dev-tools",
    icon: "sentry.png",
    defaultPrompt: "Investigate this issue in read-only Sentry data and report likely root cause, impact, and next steps.",
    installSource: { type: "bundled" },
    tags: ["sentry", "errors"],
  },
  {
    id: "playwright",
    displayName: "Playwright",
    shortDescription: "Automate real browsers from the terminal",
    category: "dev-tools",
    icon: "playwright.png",
    defaultPrompt: "Automate this browser workflow with Playwright and produce a reliable script with run steps.",
    installSource: { type: "bundled" },
    tags: ["playwright", "browser"],
  },
  {
    id: "screenshot",
    displayName: "Screenshot",
    shortDescription: "Capture screenshots",
    category: "dev-tools",
    icon: "screenshot.png",
    defaultPrompt: "Capture the right screenshot for this task (target, area, and output path).",
    installSource: { type: "bundled" },
    tags: ["screenshot", "capture"],
  },
  {
    id: "jupyter-notebook",
    displayName: "Jupyter Notebooks",
    shortDescription: "Create Jupyter notebooks",
    category: "dev-tools",
    icon: "jupyter.png",
    defaultPrompt: "Create a Jupyter notebook for this task with clear sections, runnable cells, and concise takeaways.",
    installSource: { type: "bundled" },
    tags: ["jupyter", "notebook"],
  },
  {
    id: "openai-docs",
    displayName: "OpenAI Docs",
    shortDescription: "Reference official OpenAI developer docs",
    category: "docs",
    icon: "openai.png",
    defaultPrompt: "Use the latest OpenAI docs to ground this implementation before writing code.",
    installSource: { type: "bundled" },
    tags: ["openai", "docs"],
  },
  {
    id: "chatgpt-apps",
    displayName: "ChatGPT Apps",
    shortDescription: "Build and scaffold ChatGPT apps",
    category: "dev-tools",
    icon: "openai.png",
    defaultPrompt: "Use $chatgpt-apps to classify the app archetype first, then fetch current OpenAI Apps SDK docs before generating code.",
    installSource: { type: "bundled" },
    tags: ["chatgpt", "apps", "sdk"],
  },
  {
    id: "develop-web-game",
    displayName: "Develop Web Game",
    shortDescription: "Web game dev with a Playwright validation loop",
    category: "creative",
    icon: "game.png",
    defaultPrompt: "Build and iterate a playable web game in this workspace, validating changes with a Playwright loop.",
    installSource: { type: "bundled" },
    tags: ["game", "creative"],
  },
  {
    id: "yeet",
    displayName: "Yeet",
    shortDescription: "Stage, commit, and open PR",
    category: "dev-tools",
    icon: "yeet.png",
    defaultPrompt: "Prepare this branch for review: stage intended changes, write a focused commit, and open a PR.",
    installSource: { type: "bundled" },
    tags: ["git", "commit", "pr"],
  },
  {
    id: "notion-knowledge-capture",
    displayName: "Notion Knowledge Capture",
    shortDescription: "Capture conversations into structured Notion pages",
    category: "productivity",
    icon: "notion.png",
    defaultPrompt: "Capture this conversation into structured Notion pages with decisions, action items, and owners when known.",
    dependencies: [{ type: "mcp", value: "notion", description: "Notion MCP server", url: "https://mcp.notion.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["notion", "knowledge"],
  },
  {
    id: "notion-meeting-intelligence",
    displayName: "Notion Meeting Intelligence",
    shortDescription: "Prep meetings with Notion context",
    category: "productivity",
    icon: "notion.png",
    defaultPrompt: "Prepare this meeting from Notion context with a brief, agenda, decisions needed, and open questions.",
    dependencies: [{ type: "mcp", value: "notion", description: "Notion MCP server", url: "https://mcp.notion.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["notion", "meeting"],
  },
  {
    id: "notion-research-documentation",
    displayName: "Notion Research & Documentation",
    shortDescription: "Research Notion content and produce briefs",
    category: "productivity",
    icon: "notion.png",
    defaultPrompt: "Research this topic in Notion and produce a sourced brief with clear recommendations.",
    dependencies: [{ type: "mcp", value: "notion", description: "Notion MCP server", url: "https://mcp.notion.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["notion", "research"],
  },
  {
    id: "notion-spec-to-implementation",
    displayName: "Notion Spec to Implementation",
    shortDescription: "Turn Notion specs into implementation plans",
    category: "productivity",
    icon: "notion.png",
    defaultPrompt: "Turn this Notion spec into an implementation plan with milestones, tasks, and dependencies.",
    dependencies: [{ type: "mcp", value: "notion", description: "Notion MCP server", url: "https://mcp.notion.com/mcp" }],
    installSource: { type: "bundled" },
    tags: ["notion", "spec", "planning"],
  },
  {
    id: "pdf",
    displayName: "PDF",
    shortDescription: "Create, edit, and review PDFs",
    category: "productivity",
    icon: "pdf.png",
    defaultPrompt: "Create, edit, or review this PDF and summarize the key output or changes.",
    installSource: { type: "bundled" },
    tags: ["pdf", "document"],
  },
  {
    id: "doc",
    displayName: "Word Docs",
    shortDescription: "Edit and review docx files",
    category: "productivity",
    icon: "doc.png",
    defaultPrompt: "Edit or review this .docx file and return the updated file plus a concise change summary.",
    installSource: { type: "bundled" },
    tags: ["docx", "word"],
  },
  {
    id: "spreadsheet",
    displayName: "Spreadsheet",
    shortDescription: "Create, edit, and analyze spreadsheets",
    category: "productivity",
    icon: "spreadsheet.png",
    defaultPrompt: "Create or update a spreadsheet for this task with the right formulas, structure, and formatting.",
    installSource: { type: "bundled" },
    tags: ["spreadsheet", "data"],
  },
  {
    id: "imagegen",
    displayName: "Image Gen",
    shortDescription: "Generate and edit images using OpenAI",
    category: "creative",
    icon: "imagegen.png",
    defaultPrompt: "Generate or edit images for this task and return the final prompt plus selected outputs.",
    dependencies: [{ type: "api-key", value: "OPENAI_API_KEY", description: "OpenAI API key for image generation" }],
    installSource: { type: "bundled" },
    tags: ["image", "openai"],
  },
  {
    id: "sora",
    displayName: "Sora",
    shortDescription: "Generate and manage Sora videos",
    category: "creative",
    icon: "sora.png",
    defaultPrompt: "Plan and generate a Sora video for this request, then iterate with concrete prompt edits.",
    dependencies: [{ type: "api-key", value: "OPENAI_API_KEY", description: "OpenAI API key for Sora" }],
    installSource: { type: "bundled" },
    tags: ["sora", "video"],
  },
  {
    id: "speech",
    displayName: "Speech",
    shortDescription: "Generate narrated audio from text",
    category: "creative",
    icon: "speech.png",
    defaultPrompt: "Generate spoken audio for this text with the right voice style, pacing, and output format.",
    dependencies: [{ type: "api-key", value: "OPENAI_API_KEY", description: "OpenAI API key for speech" }],
    installSource: { type: "bundled" },
    tags: ["speech", "audio"],
  },
  {
    id: "transcribe",
    displayName: "Transcribe",
    shortDescription: "Transcribe audio with speaker diarization",
    category: "creative",
    icon: "transcribe.png",
    defaultPrompt: "Transcribe this audio and return timestamped speaker-attributed text plus a concise summary.",
    dependencies: [{ type: "api-key", value: "OPENAI_API_KEY", description: "OpenAI API key for transcription" }],
    installSource: { type: "bundled" },
    tags: ["transcribe", "audio"],
  },
  {
    id: "security-best-practices",
    displayName: "Security Best Practices",
    shortDescription: "Security reviews and secure-by-default guidance",
    category: "security",
    icon: "security-best-practices.png",
    defaultPrompt: "Review this implementation for security risks and provide concrete, prioritized fixes.",
    installSource: { type: "bundled" },
    tags: ["security", "review"],
  },
  {
    id: "security-ownership-map",
    displayName: "Security Ownership Map",
    shortDescription: "Map maintainers, bus factor, and sensitive code ownership",
    category: "security",
    icon: "security-ownership-map.png",
    defaultPrompt: "Map ownership of security-sensitive areas and highlight coverage gaps and risks.",
    installSource: { type: "bundled" },
    tags: ["security", "ownership"],
  },
  {
    id: "security-threat-model",
    displayName: "Security Threat Model",
    shortDescription: "Threat modeling and abuse-path analysis",
    category: "security",
    icon: "security-threat-model.png",
    defaultPrompt: "Create a repository-grounded threat model for this codebase with prioritized abuse paths and mitigations.",
    installSource: { type: "bundled" },
    tags: ["security", "threat-model"],
  },
  {
    id: "aspnet-core",
    displayName: "ASP.NET Core",
    shortDescription: "[Windows] Build and review ASP.NET Core web apps",
    category: "dev-tools",
    icon: "dotnet.png",
    defaultPrompt: "Create a new ASP.NET Core website for me.",
    installSource: { type: "bundled" },
    tags: ["dotnet", "windows"],
    platforms: ["windows"],
  },
  {
    id: "winui-app",
    displayName: "WinUI App",
    shortDescription: "[Windows] Build native WinUI 3 apps",
    category: "dev-tools",
    icon: "winui.png",
    defaultPrompt: "Create a new WinUI 3 desktop app for me.",
    installSource: { type: "bundled" },
    tags: ["winui", "windows"],
    platforms: ["windows"],
  },
];

export const CATALOG_COLLECTIONS: CatalogSkillCollection[] = [];

export { AGENCY_AGENTS_COLLECTION, SYSTEM_SKILLS };

export function getAllCatalogSkills(): CatalogSkill[] {
  // Agency agents are now surfaced in the agent creation wizard (template picker),
  // not in the skills catalog page.
  return [...SYSTEM_SKILLS, ...SKILL_CATALOG];
}

export function getCatalogSkillById(skillId: string): CatalogSkill | undefined {
  return getAllCatalogSkills().find((skill) => skill.id === skillId);
}

export function getCatalogCollections(): CatalogSkillCollection[] {
  return [...CATALOG_COLLECTIONS];
}

export function getCatalogSkillsByCollection(collectionId: string): CatalogSkill[] {
  return getAllCatalogSkills().filter((skill) => skill.collectionId === collectionId);
}
